language: java

env:
  global:
    - secure "${CODECOV_TOKEN}"

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "cooltools"
    token:
      secure: "${SONARCLOUD_TOKEN}"
script:
  - sonar-scanner
