language: java

env:
  global:
    - secure "${CODECOV_TOKEN}"

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "cooltools"
    token:
      secure: "${SONARCLOUD_TOKEN}"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=shenuhan_dev.cooltools.docx
